// 1. Interfaz para mantener el tipado fuerte en todo el sistema
export interface SelectOption {
  label: string;
  value: string;
}

// 2. Constante exportada para Documentos de Identidad
export const DOCUMENT_TYPE_OPTIONS: SelectOption[] = [
  { label: 'CI (Bolivia)', value: 'CI' },
  { label: 'DNI (Perú)', value: 'DNI' },
];

// 3. Constante exportada para Canal de Origen
export const HOW_DID_YOU_FIND_US_OPTIONS: SelectOption[] = [
  { label: 'Redes Sociales (Facebook, Instagram, etc.)', value: 'REDES_SOCIALES' },
  { label: 'Buscador de Internet (Google, Bing)', value: 'BUSCADOR' },
  { label: 'Recomendación (Boca a boca)', value: 'RECOMENDACION' },
  { label: 'Publicidad en Internet (Anuncios)', value: 'PUBLICIDAD_ONLINE' },
  { label: 'Correo electrónico / Newsletter', value: 'CORREO_ELECTRONICO' },
  { label: 'Prensa, blog o artículo de noticias', value: 'PRENSA_BLOG' },
  { label: 'Evento, feria o conferencia', value: 'EVENTO' },
  { label: 'Radio o Televisión', value: 'MEDIOS_TRADICIONALES' },
  { label: 'Publicidad impresa (Folletos, carteles)', value: 'PUBLICIDAD_IMPRESA' },
  { label: 'Alianza comercial / Empresa asociada', value: 'ALIANZA_COMERCIAL' },
  { label: 'Código QR', value: 'CODIGO_QR' },
  { label: 'Tarjeta de presentación', value: 'TARJETA_PRESENTACION' },
  { label: 'Ya era cliente / Conocía la marca', value: 'CLIENTE_EXISTENTE' },
  { label: 'Otro', value: 'OTRO' }
];

// 4. Constante exportada para Ocupaciones
export const OCCUPATION_OPTIONS: SelectOption[] = [
  { label: 'Abogado', value: 'ABOGADO' },
  { label: 'Actor / Actriz', value: 'ACTOR_ACTRIZ' },
  { label: 'Administrador de Empresas', value: 'ADMINISTRADOR_EMPRESAS' },
  { label: 'Agricultor / Ganadero', value: 'AGRICULTOR_GANADERO' },
  { label: 'Albañil', value: 'ALBANIL' },
  { label: 'Almacenero / Bodeguero', value: 'ALMACENERO_BODEGUERO' },
  { label: 'Analista de Datos', value: 'ANALISTA_DATOS' },
  { label: 'Arquitecto', value: 'ARQUITECTO' },
  { label: 'Artesano', value: 'ARTESANO' },
  { label: 'Asistente Administrativo', value: 'ASISTENTE_ADMINISTRATIVO' },
  { label: 'Asistente Social', value: 'ASISTENTE_SOCIAL' },
  { label: 'Auditor', value: 'AUDITOR' },
  { label: 'Biólogo', value: 'BIOLOGO' },
  { label: 'Bombero', value: 'BOMBERO' },
  { label: 'Cajero', value: 'CAJERO' },
  { label: 'Camarero / Mesero', value: 'CAMARERO_MESERO' },
  { label: 'Camionero / Conductor', value: 'CAMIONERO_CONDUCTOR' },
  { label: 'Carpintero', value: 'CARPINTERO' },
  { label: 'Cartero / Repartidor', value: 'CARTERO_REPARTIDOR' },
  { label: 'Científico', value: 'CIENTIFICO' },
  { label: 'Cirujano', value: 'CIRUJANO' },
  { label: 'Cocinero / Chef', value: 'COCINERO_CHEF' },
  { label: 'Comerciante / Vendedor', value: 'COMERCIANTE_VENDEDOR' },
  { label: 'Contador / Contable', value: 'CONTADOR_CONTABLE' },
  { label: 'Consultor', value: 'CONSULTOR' },
  { label: 'Diseñador Gráfico', value: 'DISENADOR_GRAFICO' },
  { label: 'Diseñador Web', value: 'DISENADOR_WEB' },
  { label: 'Economista', value: 'ECONOMISTA' },
  { label: 'Electricista', value: 'ELECTRICISTA' },
  { label: 'Empleado Doméstico', value: 'EMPLEADO_DOMESTICO' },
  { label: 'Enfermero', value: 'ENFERMERO' },
  { label: 'Entrenador Físico', value: 'ENTRENADOR_FISICO' },
  { label: 'Escritor / Redactor', value: 'ESCRITOR_REDACTOR' },
  { label: 'Esteticista / Estilista', value: 'ESTETICISTA_ESTILISTA' },
  { label: 'Estudiante', value: 'ESTUDIANTE' },
  { label: 'Farmacéutico', value: 'FARMACEUTICO' },
  { label: 'Filósofo', value: 'FILOSOFO' },
  { label: 'Fisioterapeuta', value: 'FISIOTERAPEUTA' },
  { label: 'Fontanero / Plomero', value: 'FONTANERO_PLOMERO' },
  { label: 'Fotógrafo', value: 'FOTOGRAFO' },
  { label: 'Geólogo', value: 'GEOLOGO' },
  { label: 'Gerente / Director', value: 'GERENTE_DIRECTOR' },
  { label: 'Guardia de Seguridad', value: 'GUARDIA_SEGURIDAD' },
  { label: 'Guía Turístico', value: 'GUIA_TURISTICO' },
  { label: 'Historiador', value: 'HISTORIADOR' },
  { label: 'Ingeniero Civil', value: 'INGENIERO_CIVIL' },
  { label: 'Ingeniero de Software / Programador', value: 'INGENIERO_SOFTWARE' },
  { label: 'Ingeniero Eléctrico', value: 'INGENIERO_ELECTRICO' },
  { label: 'Ingeniero Industrial', value: 'INGENIERO_INDUSTRIAL' },
  { label: 'Ingeniero Mecánico', value: 'INGENIERO_MECANICO' },
  { label: 'Ingeniero Químico', value: 'INGENIERO_QUIMICO' },
  { label: 'Inspector de Calidad', value: 'INSPECTOR_CALIDAD' },
  { label: 'Investigador', value: 'INVESTIGADOR' },
  { label: 'Jardinero', value: 'JARDINERO' },
  { label: 'Juez', value: 'JUEZ' },
  { label: 'Jefatura de Proyecto', value: 'JEFATURA_PROYECTO' },
  { label: 'Limpiador / Personal de Aseo', value: 'LIMPIADOR_ASEO' },
  { label: 'Maestro / Profesor', value: 'MAESTRO_PROFESOR' },
  { label: 'Maquillador', value: 'MAQUILLADOR' },
  { label: 'Marinero / Pescador', value: 'MARINERO_PESCADOR' },
  { label: 'Mecánico', value: 'MECANICO' },
  { label: 'Médico / Doctor', value: 'MEDICO_DOCTOR' },
  { label: 'Militar', value: 'MILITAR' },
  { label: 'Minero', value: 'MINERO' },
  { label: 'Modelo', value: 'MODELO' },
  { label: 'Músico', value: 'MUSICO' },
  { label: 'Nutricionista', value: 'NUTRICIONISTA' },
  { label: 'Odontólogo / Dentista', value: 'ODONTOLOGO_DENTISTA' },
  { label: 'Operador de Maquinaria', value: 'OPERADOR_MAQUINARIA' },
  { label: 'Panadero / Pastelero', value: 'PANADERO_PASTELERO' },
  { label: 'Paramédico', value: 'PARAMEDICO' },
  { label: 'Peluquero / Barbero', value: 'PELUQUERO_BARBERO' },
  { label: 'Periodista', value: 'PERIODISTA' },
  { label: 'Piloto de Aviación', value: 'PILOTO_AVIACION' },
  { label: 'Pintor', value: 'PINTOR' },
  { label: 'Policía', value: 'POLICIA' },
  { label: 'Político', value: 'POLITICO' },
  { label: 'Psicólogo', value: 'PSICOLOGO' },
  { label: 'Psiquiatra', value: 'PSIQUIATRA' },
  { label: 'Publicista', value: 'PUBLICISTA' },
  { label: 'Recepcionista', value: 'RECEPCIONISTA' },
  { label: 'Relaciones Públicas', value: 'RELACIONES_PUBLICAS' },
  { label: 'Reportero', value: 'REPORTERO' },
  { label: 'Secretaria / Secretario', value: 'SECRETARIA_SECRETARIO' },
  { label: 'Sociólogo', value: 'SOCIOLOGO' },
  { label: 'Soporte Técnico', value: 'SOPORTE_TECNICO' },
  { label: 'Sastre / Modista', value: 'SASTRE_MODISTA' },
  { label: 'Técnico de Laboratorio', value: 'TECNICO_LABORATORIO' },
  { label: 'Traductor / Intérprete', value: 'TRADUCTOR_INTERPRETE' },
  { label: 'Tripulante de Cabina', value: 'TRIPULANTE_CABINA' },
  { label: 'Veterinario', value: 'VETERINARIO' },
  { label: 'Vigilante', value: 'VIGILANTE' },
  { label: 'Desempleado', value: 'DESEMPLEADO' },
  { label: 'Jubilado / Pensionado', value: 'JUBILADO_PENSIONADO' },
  { label: 'Otro', value: 'OTRO' }
];

// 5. Constante exportada para Origen de Fondos
export const SOURCE_OF_FUNDS_OPTIONS: SelectOption[] = [
  { label: 'Salario / Sueldo', value: 'SALARIO' },
  { label: 'Honorarios Profesionales / Ventas', value: 'HONORARIOS_VENTAS' },
  { label: 'Ahorros Personales', value: 'AHORROS' },
  { label: 'Inversiones / Rendimientos Financieros', value: 'INVERSIONES' },
  { label: 'Venta de Bienes (Inmuebles, Vehículos, etc.)', value: 'VENTA_BIENES' },
  { label: 'Alquileres / Arrendamientos', value: 'ALQUILERES' },
  { label: 'Dividendos / Utilidades Empresariales', value: 'DIVIDENDOS' },
  { label: 'Préstamo Bancario / Crédito', value: 'PRESTAMO_BANCARIO' },
  { label: 'Herencia / Legado', value: 'HERENCIA' },
  { label: 'Donación / Regalo Familiar', value: 'DONACION' },
  { label: 'Subvención / Beca / Fondo Gubernamental', value: 'SUBVENCION_GOBIERNO' },
  { label: 'Financiamiento Colectivo (Crowdfunding)', value: 'CROWDFUNDING' },
  { label: 'Inversionistas / Capital de Riesgo', value: 'INVERSIONISTAS' },
  { label: 'Otro', value: 'OTRO' }
];

// 6. Constante exportada para Nivel de Cliente (Volumen Transaccional)
export const CUSTOMER_TIER_OPTIONS: SelectOption[] = [
  { label: 'Nivel 1 - Básico (Límite Bajo)', value: 'TIER_1' },
  { label: 'Nivel 2 - Intermedio (Límite Medio)', value: 'TIER_2' },
  { label: 'Nivel 3 - Avanzado (Límite Alto)', value: 'TIER_3' },
  { label: 'Nivel Sin Límite / Personalizado', value: 'UNLIMITED' }
];