import { Transaction } from '../models/transaction.model';

export const MOCK_TRANSACTIONS: Transaction[] = [
  // Transacción finalizada
  {
    id: 'txn-001',
    clientId: 'usr-001',
    clientName: 'John Doe',
    intermediaryId: 'usr-002',
    sourceAmount: 1000,
    sourceCurrency: 'BOB',
    destinationAmount: 520.83,
    destinationCurrency: 'PEN',
    appliedRate: 0.52083,
    sourceAccountId: 'acc-001',
    destinationAccountId: 'acc-002',
    destinationQrUrl: 'img/QR/qr-destino-001.jpeg',
    intermediaryQrUrl: 'assets/images/mock/qr-intermediario-001.png',
    clientReceiptUrl: 'assets/images/mock/comprobante-cliente-001.png',
    intermediaryReceiptUrl: 'img/QR/comprobante-intermediario-001.png',
    status: 'finalizado',
    denialReason: null,
    createdAt: '2024-03-01T10:00:00.000Z',
    updatedAt: '2024-03-01T14:30:00.000Z',
  },
  // Transacción pendiente de depósito (paso 1)
  {
    id: 'txn-002',
    clientId: 'usr-001',
    clientName: 'John Doe',
    intermediaryId: 'usr-002',
    sourceAmount: 500,
    sourceCurrency: 'BOB',
    destinationAmount: 260.42,
    destinationCurrency: 'PEN',
    appliedRate: 0.52083,
    sourceAccountId: 'acc-001',
    destinationAccountId: 'acc-003',
    destinationQrUrl: 'assets/images/mock/qr-destino-002.png',
    intermediaryQrUrl: 'assets/images/mock/qr-intermediario-002.png',
    clientReceiptUrl: null,
    intermediaryReceiptUrl: null,
    status: 'pendiente_deposito',
    denialReason: null,
    createdAt: '2024-03-10T09:15:00.000Z',
    updatedAt: '2024-03-10T09:15:00.000Z',
  },
  // Transacción pendiente de verificación (paso 2)
  {
    id: 'txn-003',
    clientId: 'usr-004',
    clientName: 'Jane Smith',
    intermediaryId: 'usr-002',
    sourceAmount: 2000,
    sourceCurrency: 'BOB',
    destinationAmount: 1041.67,
    destinationCurrency: 'PEN',
    appliedRate: 0.52083,
    sourceAccountId: 'acc-006',
    destinationAccountId: 'acc-007',
    destinationQrUrl: 'assets/images/mock/qr-destino-003.png',
    intermediaryQrUrl: 'assets/images/mock/qr-intermediario-003.png',
    clientReceiptUrl: 'assets/images/mock/comprobante-cliente-003.png',
    intermediaryReceiptUrl: null,
    status: 'pendiente_verificacion',
    denialReason: null,
    createdAt: '2024-03-12T11:00:00.000Z',
    updatedAt: '2024-03-12T11:45:00.000Z',
  },
  // Transacción verificada (paso 3)
  {
    id: 'txn-004',
    clientId: 'usr-001',
    clientName: 'John Doe',
    intermediaryId: 'usr-005',
    sourceAmount: 750,
    sourceCurrency: 'BOB',
    destinationAmount: 390.63,
    destinationCurrency: 'PEN',
    appliedRate: 0.52083,
    sourceAccountId: 'acc-001',
    destinationAccountId: 'acc-002',
    destinationQrUrl: 'assets/images/mock/qr-destino-004.png',
    intermediaryQrUrl: 'assets/images/mock/qr-intermediario-004.png',
    clientReceiptUrl: 'assets/images/mock/comprobante-cliente-004.png',
    intermediaryReceiptUrl: null,
    status: 'verificado',
    denialReason: null,
    createdAt: '2024-03-14T08:30:00.000Z',
    updatedAt: '2024-03-14T10:00:00.000Z',
  },
  // Transacción transferida (paso 4)
  {
    id: 'txn-005',
    clientId: 'usr-004',
    clientName: 'Jane Smith',
    intermediaryId: 'usr-005',
    sourceAmount: 300,
    sourceCurrency: 'PEN',
    destinationAmount: 576.0,
    destinationCurrency: 'BOB',
    appliedRate: 1.92,
    sourceAccountId: 'acc-007',
    destinationAccountId: 'acc-006',
    destinationQrUrl: 'assets/images/mock/qr-destino-005.png',
    intermediaryQrUrl: 'assets/images/mock/qr-intermediario-005.png',
    clientReceiptUrl: 'assets/images/mock/comprobante-cliente-005.png',
    intermediaryReceiptUrl:
      'assets/images/mock/comprobante-intermediario-005.png',
    status: 'transferido',
    denialReason: null,
    createdAt: '2024-03-15T14:00:00.000Z',
    updatedAt: '2024-03-15T16:20:00.000Z',
  },
  // Transacción denegada
  {
    id: 'txn-006',
    clientId: 'usr-001',
    clientName: 'John Doe',
    intermediaryId: 'usr-002',
    sourceAmount: 1500,
    sourceCurrency: 'BOB',
    destinationAmount: 781.25,
    destinationCurrency: 'PEN',
    appliedRate: 0.52083,
    sourceAccountId: 'acc-001',
    destinationAccountId: 'acc-002',
    destinationQrUrl: 'assets/images/mock/qr-destino-006.png',
    intermediaryQrUrl: 'assets/images/mock/qr-intermediario-006.png',
    clientReceiptUrl: 'assets/images/mock/comprobante-cliente-006.png',
    intermediaryReceiptUrl: null,
    status: 'denegado',
    denialReason:
      'El comprobante no corresponde al monto indicado. Por favor, verifique y vuelva a intentar.',
    createdAt: '2024-03-08T16:00:00.000Z',
    updatedAt: '2024-03-08T17:30:00.000Z',
  },
  // Otra transacción pendiente de verificación
  {
    id: 'txn-007',
    clientId: 'usr-001',
    clientName: 'John Doe',
    intermediaryId: 'usr-005',
    sourceAmount: 200,
    sourceCurrency: 'PEN',
    destinationAmount: 384.0,
    destinationCurrency: 'BOB',
    appliedRate: 1.92,
    sourceAccountId: 'acc-002',
    destinationAccountId: 'acc-001',
    destinationQrUrl: 'assets/images/mock/qr-destino-007.png',
    intermediaryQrUrl: 'assets/images/mock/qr-intermediario-007.png',
    clientReceiptUrl: 'assets/images/mock/comprobante-cliente-007.png',
    intermediaryReceiptUrl: null,
    status: 'pendiente_verificacion',
    denialReason: null,
    createdAt: '2024-03-16T10:30:00.000Z',
    updatedAt: '2024-03-16T11:00:00.000Z',
  },
];
